### PR TITLE
Displayed Data in a User-Friendly Format

### PR DESCRIPTION
**Pull request by roshankraveendrababu**
#5 
The following changes were made to the code to ensure that the data is presented in an user friendly manner-
User-Friendly Display: The formatted_output uses Markdown to present the data in a clear, card-like format, making it easier to read.

Formatted Species List: If the user doesn’t provide a specific species, the list of species is displayed with appropriate labels for each attribute.

Pagination: Pagination controls (previous and next buttons) allow users to browse through multiple pages of species when filtering by conservation status

the code was also considerably shortened but it retains all the functionality of the prior one with additional features

### CODE REVIEW

**Comment by kaybrian** [comment]
Hey @roshankraveendrababu I feel like it deleting alot of content for the user and data visualization at the moment, Tryy to check the updated code and see

**Review by kaybrian — CHANGES_REQUESTED** [review]
Hello @roshankraveendrababu, thank you so much for the work, I have noticed that the branch you are working on is a little bit behind the new changes from the main file and emerging it is going to cause us to loss the current changes, do you mind fetching the new data on main so that your branch gets on the same line with the new changes. ?

**Comment by roshankraveendrababu** [comment]
> Hello @roshankraveendrababu, thank you so much for the work, I have noticed that the branch you are working on is a little bit behind the new changes from the main file and emerging it is going to cause us to loss the current changes, do you mind fetching the new data on main so that your branch gets on the same line with the new changes. ?

really bro! in my repo its say that i'm in sync with the parent repo and 1 commit ahead.

**Comment by roshankraveendrababu** [comment]
can you create an new issue in the same name and assign me. i have completed the code but there was an glitch of some sorts so i had to deleted the forked repo and re- fork it . 
sorry for the inconvinience. can you please!

**Comment by roshankraveendrababu** [comment]
can you create an new issue in the same name and assign me. i have completed the code but there was an glitch of some sorts so i had to deleted the forked repo and re- fork it .
sorry for the inconvinience. can you please!

**Comment by kaybrian** [comment]
sure i got you, lt me open it up now.

**Pull request closed without merging**
